package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Date;
import java.util.*;

import com.example.jdbcdemo.domain.Person;

public class DeviceManagerJDBC implements PersonManager{

	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTableDevice = "CREATE TABLE Device(id bigint GENERATED BY DEFAULT AS IDENTITY, deviceName varchar(40) UNIQUE NOT NULL, screenSize double NOT NULL, dateOfRelease date NOT NULL)";
	private String createTableComponents = "CREATE TABLE Components(id bigint GENERATED BY DEFAULT AS IDENTITY, devicename varchar(40) UNIQUE NOT NULL, storage int NOT NULL, memory int NOT NULL, processor varchar(20) NOT NULL)";
	private String foreignKey = "ALTER TABLE Components ADD FOREIGN KEY (deviceName) REFERENCES Device(deviceName)";

	private PreparedStatement addDeviceStmt;
	private PreparedStatement getAllDevicesStmt;
	private PreparedStatement deleteAllDevicesStmt;
	private PreparedStatement deleteDeviceByNameStmt;
	private PreparedStatement findDeviceByNameStmt;
	private PreparedStatement findDeviceByScreenSizeStmt;
	private PreparedStatement findDeviceByDate;
	private PreparedStatement updateDeviceByNameStmt;



	private Statement statement;

	public DeviceManagerJDBC() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,null);
			boolean tableDeviceExists = false;
			boolean tablecomponentsExists = false;
			while (rs.next()) {
				if ("Device".equalsIgnoreCase(rs.getString("TABLE_NAME")))
					tableDeviceExists = true;

				if("Components".equalsIgnoreCase(rs.getNString("TABLE_NAME")))
					tablecomponentsExists = true;

				if(tableDeviceExists && tablecomponentsExists)
					break;

			}

			if (!tableDeviceExists)
				statement.executeUpdate(createTableDevice);
			if (!tablecomponentsExists){
				statement.executeUpdate(createTableComponents);
				statement.executeUpdate(foreignKey);
			}

			addDeviceStmt = connection
					.prepareStatement("INSERT INTO Device (deviceName, screenSize, dateOfRelease) VALUES (?, ?, ?)");
			deleteAllDevicesStmt = connection
					.prepareStatement("DELETE FROM Device");
			getAllDevicesStmt = connection
					.prepareStatement("SELECT id, deviceName, screenSize, dateOfRelease FROM Device");
			deleteDeviceByNameStmt = connection
					.prepareStatement("DELETE FROM Device WHERE deviceName = ?");
			findDeviceByNameStmt = connection
					.prepareStatement("SELECT id, deviceName, screenSize, dateOfRelease FROM Device WHERE deviceName = ?");
			findDeviceByScreenSizeStmt = connection
					.prepareStatement("SELECT id, deviceName, screenSize, dateOfRelease FROM Device WHERE ScreenSize = ?");
			findDeviceByDate = connection
					.prepareStatement("SELECT id, deviceName, screenSize, dateOfRelease FROM Device WHERE dateOfRelease = ?");
			updateDeviceByNameStmt = connection
					.prepareStatement("UPDATE Device SET deviceName = ?, screenSize = ?, dateOfRelease = ? WHERE deviceName = ?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}

	void clearDevices() {
		try {
			deleteAllDevicesStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public int addDevice(Person person) {
		int count = 0;

		try {
			addDeviceStmt.setString(1, person.getDeviceName());
			addDeviceStmt.setDouble(2, person.getScreenSize());
			addDeviceStmt.setDate(3, new Date(person.getDateOfRelease().getTimeInMillis()));

			count = addDeviceStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

	@Override
	public List<Person> getAllDevices() {
		List<Person> persons = new ArrayList<>();

		try {
			ResultSet rs = getAllDevicesStmt.executeQuery();

			persons = getFromResultSet(rs);

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return persons;
	}

	@Override
	public List<Person> findDevicesByName(Person person){
		List<Person> persons = new ArrayList<>();

		try{
			findDeviceByNameStmt.setString(1, person.getDeviceName());

			persons = getFromResultSet(findDeviceByNameStmt.executeQuery());

		}catch (SQLException e){
			e.printStackTrace();
		}
		return persons;
	}

	@Override
	public  List<Person> findDevicesByScreenSize(Person person){
		List<Person> persons = new ArrayList<>();

		try{
			findDeviceByScreenSizeStmt.setDouble(1, person.getScreenSize());
			persons = getFromResultSet(findDeviceByScreenSizeStmt.executeQuery());

		}catch (SQLException e){
			e.printStackTrace();
		}
		return persons;
	}

	@Override
	public List<Person> findDevicesByDate(Person person){
		List<Person> persons = new ArrayList<>();

		try{
			findDeviceByDate.setDate(1, new Date(person.getDateOfRelease().getTimeInMillis()));
			persons = getFromResultSet(findDeviceByDate.executeQuery());

		}catch (SQLException e){
			e.printStackTrace();
		}
		return  persons;
	}

	@Override
	public int updateDevice(Person person, Person newPerson){
		int count = 0;

		try{
			updateDeviceByNameStmt.setString(1, newPerson.getDeviceName());
			updateDeviceByNameStmt.setDouble(2, newPerson.getScreenSize());
			updateDeviceByNameStmt.setDate(3, new Date(newPerson.getDateOfRelease().getTimeInMillis()));
			updateDeviceByNameStmt.setString(4, person.getDeviceName());

			count = updateDeviceByNameStmt.executeUpdate();
		}catch (SQLException e){
			e.printStackTrace();
		}

		return count;
	}

	@Override
	public int removeDevicesByName(Person person){
		int count = 0;

		try {
			deleteDeviceByNameStmt.setString(1, person.getDeviceName());
			count = deleteDeviceByNameStmt.executeUpdate();

		}catch (SQLException e){
			e.printStackTrace();
		}
		return count;
	}

	@Override
	public void addDevices(List<Person> persons){
		try {
			connection.setAutoCommit(false);
			for (Person person : persons) {
				addDeviceStmt.setString(1, person.getDeviceName());
				addDeviceStmt.setDouble(2, person.getScreenSize());
				addDeviceStmt.setDate(3, new Date(person.getDateOfRelease().getTimeInMillis()));
				addDeviceStmt.executeUpdate();
			}
			connection.commit();
						
			} catch (SQLException exception) {
						
				try {
					connection.rollback();
					} catch (SQLException e) {
						e.printStackTrace();
						//!!!! ALARM
					}
			}
	}

	@Override
	public void updateDevices(List<Person> persons, List<Person> newPersons){
		try{
			int i = -1;

			connection.setAutoCommit(false);

			if(persons.size() != newPersons.size()){
				throw new SQLException();
			}

			for(Person person : newPersons){
				updateDeviceByNameStmt.setString(1, person.getDeviceName());
				updateDeviceByNameStmt.setDouble(2, person.getScreenSize());
				updateDeviceByNameStmt.setDate(3, new Date(person.getDateOfRelease().getTimeInMillis()));
				updateDeviceByNameStmt.setString(4, persons.get(++i).getDeviceName());
				updateDeviceByNameStmt.executeUpdate();
			}
			connection.commit();

		}catch (SQLException exception){

			try{
				connection.rollback();
			}catch (SQLException e){
				e.printStackTrace();
			}
		}
	}

	@Override
	public int deleteDevices(List<Person> persons){

		int count = 0;
		try{

			connection.setAutoCommit(false);

			for(Person person : persons){
				deleteDeviceByNameStmt.setString(1, person.getDeviceName());
				count += deleteDeviceByNameStmt.executeUpdate();

			}
			connection.commit();

		}catch (SQLException exception){

			try{
				connection.rollback();
			}catch (SQLException e){
				e.printStackTrace();
			}
		}
		return count;
	}

	private List<Person> getFromResultSet (ResultSet rs){
		List<Person> persons = new ArrayList<>();

		try {

			while (rs.next()) {
				Person p = new Person();
				Calendar c = new GregorianCalendar();
				p.setId(rs.getInt("id"));
				p.setDeviceName(rs.getString("deviceName"));
				p.setScreenSize(rs.getDouble("screenSize"));
				c.setTime(rs.getDate("dateOfRelease"));
				p.setDateOfRelease(c);
				persons.add(p);
			}
		}catch (SQLException e){
			e.printStackTrace();
		}

		return persons;
	}

}
