package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;

import com.example.jdbcdemo.domain.Person;

public class DeviceManagerJDBC implements PersonManager{

	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTableDevice = "CREATE TABLE Device(id bigint GENERATED BY DEFAULT AS IDENTITY, deviceName varchar(40), screenSize double, dateOfRelease date)";

	private PreparedStatement addDeviceStmt;
	private PreparedStatement deleteAllDevicesStmt;
	private PreparedStatement getAllDevicesStmt;
	private PreparedStatement deleteDeviceByName;

	private Statement statement;

	public DeviceManagerJDBC() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Device".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableDevice);

			addDeviceStmt = connection
					.prepareStatement("INSERT INTO Device (deviceName, screenSize, dateOfRelease) VALUES (?, ?, ?)");
			deleteAllDevicesStmt = connection
					.prepareStatement("DELETE FROM Device");
			getAllDevicesStmt = connection
					.prepareStatement("SELECT id, deviceName, screenSize, dateOfRelease FROM Device");
			deleteDeviceByName = connection
					.prepareStatement("DELETE FROM Device WHERE deviceName = ?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}

	void clearDevices() {
		try {
			deleteAllDevicesStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public int addDevice(Person person) {
		int count = 0;

		try {
			addDeviceStmt.setString(1, person.getDeviceName());
			addDeviceStmt.setDouble(2, person.getScreenSize());
			addDeviceStmt.setDate(3, new java.sql.Date(person.getDateOfRelease().getTimeInMillis()));

			count = addDeviceStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

	@Override
	public List<Person> getAllDevices() {
		List<Person> persons = new ArrayList<Person>();

		try {
			ResultSet rs = getAllDevicesStmt.executeQuery();

			while (rs.next()) {
				Person p = new Person();
				Calendar c = new GregorianCalendar();
				p.setId(rs.getInt("id"));
				p.setDeviceName(rs.getString("deviceName"));
				p.setScreenSize(rs.getDouble("screenSize"));
				c.setTime(rs.getDate("dateOfRelease"));
				p.setDateOfRelease(c);
				persons.add(p);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return persons;
	}

	@Override
	public int removeDevicesByName(Person person){
		int count = 0;

		try {
			deleteDeviceByName.setString(1, person.getDeviceName());
			count++;
		}catch (SQLException e){
			e.printStackTrace();
		}
		return count;
	}
}
