package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;

import com.example.jdbcdemo.domain.Person;

public class DeviceManagerJDBC implements PersonManager{

	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTableDevice = "CREATE TABLE Device(id bigint GENERATED BY DEFAULT AS IDENTITY, deviceName varchar(40), screenSize double, dateOfRelease date)";

	private PreparedStatement addDeviceStmt;
	private PreparedStatement deleteAllDevicesStmt;
	private PreparedStatement getAllDevicesStmt;
	private PreparedStatement deleteDeviceByNameStmt;
	private PreparedStatement findDeviceByNameStmt;
	private PreparedStatement findDeviceByScreenSizeStmt;
	private PreparedStatement updateDeviceByNameStmt;

	private Statement statement;

	public DeviceManagerJDBC() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Device".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableDevice);

			addDeviceStmt = connection
					.prepareStatement("INSERT INTO Device (deviceName, screenSize, dateOfRelease) VALUES (?, ?, ?)");
			deleteAllDevicesStmt = connection
					.prepareStatement("DELETE FROM Device");
			getAllDevicesStmt = connection
					.prepareStatement("SELECT id, deviceName, screenSize, dateOfRelease FROM Device");
			deleteDeviceByNameStmt = connection
					.prepareStatement("DELETE FROM Device WHERE deviceName = ?");
			findDeviceByNameStmt = connection
					.prepareStatement("SELECT id, deviceName, screenSize, dateOfRelease FROM Device WHERE deviceName = ?");
			findDeviceByScreenSizeStmt = connection
					.prepareStatement("SELECT id, deviceName, screenSize, dateOfRelease FROM Device WHERE ScreenSize = ?");
			updateDeviceByNameStmt = connection
					.prepareStatement("UPDATE Device SET deviceName = ?, screenSize = ?, dateOfRelease = ? WHERE deviceName = ?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}

	void clearDevices() {
		try {
			deleteAllDevicesStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public int addDevice(Person person) {
		int count = 0;

		try {
			addDeviceStmt.setString(1, person.getDeviceName());
			addDeviceStmt.setDouble(2, person.getScreenSize());
			addDeviceStmt.setDate(3, new java.sql.Date(person.getDateOfRelease().getTimeInMillis()));

			count = addDeviceStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

	@Override
	public List<Person> getAllDevices() {
		List<Person> persons = new ArrayList<Person>();

		try {
			ResultSet rs = getAllDevicesStmt.executeQuery();

			persons = getFromResultSet(rs);

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return persons;
	}

	@Override
	public int removeDevicesByName(Person person){
		int count = 0;

		try {
			deleteDeviceByNameStmt.setString(1, person.getDeviceName());
			count = deleteDeviceByNameStmt.executeUpdate();
		}catch (SQLException e){
			e.printStackTrace();
		}
		return count;
	}

	@Override
	public List<Person> findDevicesByName(Person person){
		List<Person> persons = new ArrayList<>();

		try{
			findDeviceByNameStmt.setString(1, person.getDeviceName());
			//ResultSet rs = findDeviceByNameStmt.executeQuery();

			persons = getFromResultSet(findDeviceByNameStmt.executeQuery());

		}catch (SQLException e){
			e.printStackTrace();
		}
		return persons;
	}

	@Override
	public  List<Person> findDevicesByScreenSize(Person person){
		List<Person> persons = new ArrayList<>();

		try{
			findDeviceByScreenSizeStmt.setDouble(1, person.getScreenSize());
			persons = getFromResultSet(findDeviceByScreenSizeStmt.executeQuery());

		}catch (SQLException e){
			e.printStackTrace();
		}
		return persons;
	}
	@Override
	public int updateDevice(Person person, Person newPerson){
		int count = 0;

		try{
			updateDeviceByNameStmt.setString(1, newPerson.getDeviceName());
			updateDeviceByNameStmt.setDouble(2, newPerson.getScreenSize());
			updateDeviceByNameStmt.setDate(3, new java.sql.Date(newPerson.getDateOfRelease().getTimeInMillis()));
			updateDeviceByNameStmt.setString(4, person.getDeviceName());

			count = updateDeviceByNameStmt.executeUpdate();
		}catch (SQLException e){
			e.printStackTrace();
		}

		return count;
	}

	List<Person> getFromResultSet (ResultSet rs){
		List<Person> persons = new ArrayList<>();

		try {

			while (rs.next()) {
				Person p = new Person();
				Calendar c = new GregorianCalendar();
				p.setId(rs.getInt("id"));
				p.setDeviceName(rs.getString("deviceName"));
				p.setScreenSize(rs.getDouble("screenSize"));
				c.setTime(rs.getDate("dateOfRelease"));
				p.setDateOfRelease(c);
				persons.add(p);
			}
		}catch (SQLException e){
			e.printStackTrace();
		}

		return persons;
	}
}
